# -*- coding: UTF-8 -*-
# This file is part of the jetson_stats package (https://github.com/rbonghi/jetson_stats or http://rnext.it).
# Copyright (c) 2022 Raffaello Bonghi.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

FROM python:3.8

RUN apt update && \
    apt install -y sudo bc && \
    rm -rf /var/lib/apt/lists/*

COPY . /jetson_stats

WORKDIR /jetson_stats

RUN sudo groupadd jetson_stats && \
    sudo /jetson_stats/tests/develop.sh -s && \
    sudo -H python -m pip install --upgrade pip && \
    sudo -H pip install tox

CMD ["sudo", "tox"]