# -*- coding: UTF-8 -*-
# This file is part of the jetson_stats package (https://github.com/rbonghi/jetson_stats or http://rnext.it).
# Copyright (c) 2019-2023 Raffaello Bonghi.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

ARG PYTHON_VERSION=3.12.0a3-slim-bullseye
FROM python:${PYTHON_VERSION}

RUN apt-get update && \
    apt-get install -y sudo bc && \
    rm -rf /var/lib/apt/lists/*

COPY . /jetson_stats

WORKDIR /jetson_stats

RUN sudo groupadd jtop && \
    sudo -H python -m pip install --upgrade pip && \
    sudo -H pip install tox

# Run tox
RUN sudo tox -e py${PYTHON_VERSION%.*}

CMD ["bash"]