#!/bin/bash
# This file is part of the jetson_stats package (https://github.com/rbonghi/jetson_stats or http://rnext.it).
# Copyright (c) 2019-2023 Raffaello Bonghi.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

main()
{

    if [ $(id -u) -ne 0 ] ; then
        echo "Please run as root"
        exit 1
    fi

    if [ "$#" -lt 2 ]; then
    echo "FAKE systemctl ERROR: You must provide at least 2 arguments"
    exit 1
    fi

    local COMMAND=$1

    if [[ ! "start stop restart enable disable" =~ (^|[[:space:]])"$COMMAND"($|[[:space:]]) ]]; then
    echo "FAKE systemctl ERROR: The first argument must be 'start', 'stop', 'restart', 'enable', or 'disable'"
    exit 1
    fi

    local SERVICE=$2

    if [ "$SERVICE" != "nvfancontrol" ]; then
    echo "FAKE systemctl ERROR: The second argument must be 'nvfancontrol'"
    exit 1
    fi
    
    # echo "$COMMAND $SERVICE"
}

main $@
exit 0

# EOF
