#!/bin/bash
# This file is part of the jetson_stats package (https://github.com/rbonghi/jetson_stats or http://rnext.it).
# Copyright (c) 2019-2023 Raffaello Bonghi.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

main()
{

    if [ $(id -u) -ne 0 ] ; then
        echo "Please run as root"
        exit 1
    fi

    if [ "$#" -lt 2 ]; then
    echo "FAKE systemctl ERROR: You must provide at least 2 arguments"
    exit 1
    fi

    local COMMAND=""
    local SERVICE=""
    local quiet=false

    # Decode all information from startup
    while [ -n "$1" ]; do
        case "$1" in
            start|stop|restart|enable|disable|is-active)
                COMMAND=$1
            ;;
            --quiet)
                quiet=true
            ;;
            nvfancontrol)
                SERVICE=$1
            ;;
        esac
        shift 1
    done
    
    # echo "$COMMAND $SERVICE"

    if [[ "$COMMAND" == "is-active" ]]; then
        if [ -f "/tmp/nvfancontrol_tmp" ] ; then
            exit 0
        fi
        exit 1
    elif [[ "$COMMAND" == "start" ]]; then
        touch /tmp/nvfancontrol_tmp
    elif [[ "$COMMAND" == "stop" ]]; then
        rm /tmp/nvfancontrol_tmp
    fi
}

main $@
exit 0

# EOF
