#!/bin/bash
# Emulator for NVIDIA Jetson tegrastats

usage()
{
	if [ "$1" != "" ]; then
    	tput setaf 1
		echo "$1"
		tput sgr0
	fi
	
    echo "tegrastats, Emulator of NVIDIA Jetsons"
    echo "Usage:"
    echo "$0 [options]"
    echo "options,"
    echo "   -h|--help    | This help"
    echo "   --interval   | Frequency interval"
}

main()
{
    local INTERVAL=500
    
	# Decode all information from startup
    while [ -n "$1" ]; do
        case "$1" in
            --interval)
                INTERVAL=$2
                shift 1
                ;;
            *)
                usage "[ERROR] Unknown option: $1"
                exit 1
            ;;
        esac
            shift 1
    done
    
    # Evaluate time
    INTERVAL=$(echo "scale=2; $INTERVAL/1000" | bc)
    
    while true; do 
        # Run example output for tegrastats
        echo "RAM 4722/7844MB (lfb 1x512kB) CPU [55%@2035,14%@2034,27%@2034,55%@2035,47%@2035,45%@2035] EMC_FREQ 2%@1866 GR3D_FREQ 71%@1300 APE 150 MTS fg 0% bg 0% BCPU@45C MCPU@45C GPU@51C PLL@45C AO@47.5C Tboard@37C Tdiode@46.75C PMIC@100C thermal@46.4C VDD_IN 14025/14416 VDD_CPU 2209/2538 VDD_GPU 6854/6903 VDD_SOC 1371/1370 VDD_WIFI 19/19 VDD_DDR 2702/2702"
        # Go to sleep for an interval
        sleep $INTERVAL
    done
}

main $@
exit 0

# EOF
